# Generated by Django 5.2.10 on 2026-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_totais', models.IntegerField(default=100)),
                ('vagas_ocupadas', models.IntegerField(default=0)),
            ],
        ),
    ]
